### PR TITLE
Restricting graphite-web port form outside access

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
bugzilla: 1655433
tendrl-bug-id: Tendrl/tendrl-ansible#135

Signed-off-by: GowthamShanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Review by shtripat — COMMENTED** [review]
LGTM. Please rebase.

**Comment by GowthamShanmugam** [comment]
@mbukatov @dahorak pleae review and merge this

**Review by dahorak — APPROVED** [review]
LGTM

**Review by mbukatov — APPROVED** [review]
Looks ok.

**Pull request merged**
