### PR TITLE
add ansible tags

### PR DESCRIPTION
**Pull request by mbukatov**
Adds ansible tags for: enabling and starting of services, firewalld setup and yum installation.

Implements https://github.com/Tendrl/tendrl-ansible/issues/8

### CODE REVIEW

**Review by dahorak — APPROVED** [review]
Overall LGTM... maybe just small thing to consider:
I would change `firewalld` to `firewall` - so the tag will describe what it do, not how it do it (the detail about implementation)...
But then we could reconsider the `rpm-installation` which is somewhere in the middle between the "what" and "how" ...  so I'm ok with the current state...

**Comment by mbukatov** [comment]
@dahorak since all firewall related setup is firewalld only (without any intention to add alternative ways of setting firewall in the future) and both task file and variable uses `firewalld` and not `firewall` in it's name, I don't think it's a good idea.

**Comment by mbukatov** [comment]
@julienlim We will merge this based on result of your review. I hope this will be useful for you and that the description in README makes sense.

**Comment by julienlim** [comment]
@mbukatov Looks fine to me.  Thanks!

**Pull request merged**
