### PR TITLE
Remove machine-id check

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
tendrl-bug-id: https://github.com/Tendrl/tendrl-ansible/issues/71
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@r0h4n , @nthomas-redhat , @shtripat , @mbukatov , Please review

**Review by shtripat — COMMENTED** [review]
Looks fine as long as its not required...

**Review by mbukatov — DISMISSED** [review]
Looks ok.

**Review by mbukatov — APPROVED** [review]
Looks ok.

**Pull request merged**
