### PR TITLE
Replacing grafana.ini file path in /etc/sysconfig/grafana-server

### PR DESCRIPTION
**Pull request by mbukatov**
This pull request implements https://github.com/Tendrl/tendrl-ansible/issues/29 by reconfiguring grafana to use config files provided by tendrl-monitoring-package.

### CODE REVIEW

**Comment by rishubhjain** [comment]
@mbukatov ack, will submit changes to Monitoring integration.

**Comment by rishubhjain** [comment]
@mbukatov I have made the changes https://github.com/Tendrl/monitoring-integration/pull/81, Once merged we can test it via your PR

**Comment by mbukatov** [comment]
The changes of monitoring integration has been merged and are part of the latest snapshot build.

**Comment by mbukatov** [comment]
Works with `tendrl-monitoring-integration-1.5.1-20170914T180512.878dd96.noarch`

**Pull request merged**
